const ADD_TODO_LIST = 'demo/TODO/ADD_TODO_LIST'
const TODO_TOGGLE_STATUS = 'demo/TODO/TODO_TOGGLE_STATUS'
const TODO_CHANGE_STATUS = 'demo/TODO/TODO_CHANGE_STATUS'

export {
  ADD_TODO_LIST,
  TODO_TOGGLE_STATUS,
  TODO_CHANGE_STATUS,
}
